[package]
name = "rcu-append-buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.8.1"

[dev-dependencies]
criterion = "0.5"
parking_lot = "0.12"
append-only-vec = "0.1.8"

[[bench]]
name = "rcu_append_buffer"
harness = false
